<?php $config = array (
  'THEME' => 'default',
  'CURRENCY_RATE_UPDATE' => 0,
  'STATIC_DOMAIN' => '',
  'USE_DEFAULT_SESSION_HANDLER' => 0,
  'SSL_PAYMENT' => 0,
  'SSL_CHECKOUT' => 0,
  'SSL_CUSTOMER' => 0,
  'SSL_BACKEND' => 0,
  'SSL_DOMAIN' => '',
  'CACHE_METHOD' => 'FileCache',
  'MAIN_EMAIL' => 'shumoapp@gmail.com',
  'NOTIFICATION_EMAIL' => 'shumoapp@gmail.com',
  'NEWSLETTER_EMAIL' => 'shumoapp@gmail.com',
  'STORE_NAME' => 
  array (
    'en' => 'Livecart',
  ),
  'INVENTORY_TRACKING' => 'ENABLE_AND_DISPLAY',
  'TOP_MENU_HIDE' => 1,
  'BREADCRUMB_TITLE' => 'breadcrumbs',
  'MANUFACTURER_PAGE_LIST_STYLE' => 'MANPAGE_STYLE_ALL_IN_ONE_PAGE',
  'MANUFACTURER_PAGE_DISPLAY_ACTIVE' => 1,
  'MANUFACTURER_PAGE_PER_PAGE' => 0,
  'TRACKING_SERVICES' => 
  array (
  ),
  'EMAIL_METHOD' => 'FAKE',
  'DELIVERY_TAX' => 0,
  'DELIVERY_TAX_CLASS' => '',
  'ENABLE_MULTIADDRESS' => 0,
  'URL_REPLACE_SPECIAL_CHARS' => 1,
  'MODULE_STATS_UPDATED' => 1433373169,
  'MODULE_STATS_NEED_UPDATING' => 0,
  'LOW_STOCK' => 0,
  'SOFT_NAME' => 'LiveCart',
); ?>