<?php $config = array (
  'STORE_NAME' => 
  array (
    'en' => 'Livecart',
  ),
  'STORE_HEADLINE' => 'Store Headline',
  'TITLE_SEPARATOR' => '|',
  'TITLE_FORMAT' => 'NAME_FIRST',
  'DEFAULT_META_DESCR' => 
  array (
    'en' => '',
  ),
  'LOGO' => 'image/promo/logo_small.gif',
  'FAVICON' => 'image/promo/favicon.png',
  'THEME' => 'default',
  'DISABLE_AJAX' => 0,
  'NUM_NEWS_INDEX' => 3,
  'HOME_PAGE_SUBCATS' => 1,
  'INDEX_MAN_FILTERS' => 1,
  'INDEX_PRICE_FILTERS' => 1,
  'INDEX_META_DESCRIPTION' => 
  array (
    'en' => '',
  ),
  'INDEX_META_KEYWORDS' => 
  array (
    'en' => '',
  ),
  'HIDE_SUBCATS' => 0,
  'CATEGORY_COLUMNS' => 2,
  'CATEGORY_COL_DIRECTION' => 'CAT_VER',
  'CAT_MENU_IMAGE' => 1,
  'CAT_MENU_DESCR' => 0,
  'CAT_MENU_SUBS' => 3,
  'ALLOWED_SORT_ORDER' => 
  array (
    'FEATURED' => 1,
    'SALES_RANK' => 1,
    'RATING' => 1,
    'PRODUCT_NAME_ASC' => 1,
    'PRODUCT_NAME_DESC' => 1,
    'PRICE_ASC' => 1,
    'PRICE_DESC' => 1,
    'NEWEST_ARRIVALS' => 1,
  ),
  'SORT_ORDER' => 'FEATURED',
  'DISPLAY_NUM_CAT' => 0,
  'DISPLAY_PRICES' => 1,
  'DISPLAY_CATEGORY_DESC' => 1,
  'INCLUDE_SUBCATEGORY_PRODUCTS' => 0,
  'FEATURED_COUNT' => 10,
  'FEATURED_RANDOM' => 1,
  'DISPLAY_CATEGORY_FEATURED' => 0,
  'FEATURED_LAYOUT' => '',
  'LIST_LAYOUT' => 'LIST',
  'ENABLED_LIST_LAYOUTS' => 
  array (
    'LIST' => 1,
    'GRID' => 1,
    'TABLE' => 1,
  ),
  'NUM_PRODUCTS_PER_CAT' => 10,
  'LAYOUT_GRID_COLUMNS' => 3,
  'LAYOUT_GRID_ROWS' => 5,
  'ALLOW_SWITCH_LAYOUT' => 1,
  'TABLE_VIEW_COLUMNS' => 
  array (
    'IMAGE' => 1,
    'SKU' => 1,
    'NAME' => 1,
    'PRICE' => 1,
    'DETAILS' => 1,
  ),
  'MISSING_IMG_THUMB' => 'image/missing_mini.jpg',
  'MISSING_IMG_SMALL' => 'image/missing_small.jpg',
  'MISSING_IMG_LARGE' => 'image/missing_large.jpg',
  'DISPLAY_NUM_FILTER' => 1,
  'ENABLE_MAN_FILTERS' => 1,
  'ENABLE_PRICE_FILTERS' => 1,
  'DISPLAY_CAT_MAN_FILTERS' => 1,
  'DISPLAY_CAT_PRICE_FILTERS' => 1,
  'validate_NUM_PRODUCTS_PER_CAT' => 'MinValueCheck: <1: _err_not_positive>',
  'PRODUCT_TABS' => 1,
  'INCLUDE_BASE_TAXES' => 1,
  'SHOW_PRODUCT_WEIGHT' => 0,
  'SHOW_SKU_CART' => 0,
  'SHOW_SKU_EMAIL' => 0,
  'UNIT_SYSTEM' => 'METRIC',
  'QUANT_FIELD_TYPE' => 'QUANT_SELECT',
  'PRODUCT_PAGE_LIST_LAYOUT' => '',
  'PRODUCT_DISPLAY_STOCK' => 0,
  'PRODUCT_DISPLAY_LOW_STOCK' => 0,
  'PRODUCT_DISPLAY_NO_STOCK' => 0,
  'LOW_STOCK' => 0,
  'NUM_PURCHASED_TOGETHER' => 5,
  'ENABLE_PRODUCT_COMPARE' => 1,
  'PRODUCT_INQUIRY_FORM' => 1,
  'ENABLE_REVIEWS' => 1,
  'ENABLE_RATINGS' => 1,
  'REVIEWS_WITH_RATINGS' => 1,
  'REQUIRE_PURCHASE_TO_RATE' => 0,
  'ENABLE_ANONYMOUS_RATINGS' => 1,
  'RATING_SCALE' => 5,
  'RATING_SAME_IP_TIME' => 24,
  'APPROVE_REVIEWS' => 'APPROVE_REVIEWS_AUTO',
  'NUM_REVIEWS_IN_PRODUCT_PAGE' => 2,
  'REVIEWS_PER_PAGE' => 5,
  'validate_LOW_STOCK' => 'MinValueCheck: <1: _err_not_positive>',
  'MAX_FILTER_CRITERIA_COUNT' => 5,
  'FILTER_STYLE' => 'FILTER_STYLE_LINKS',
  'TOP_MENU_COMPACT' => 0,
  'TOP_FILTER_PRICE' => 0,
  'TOP_FILTER_MANUFACTURER' => 0,
  'TOP_FILTER_CONTINUOS' => 0,
  'TOP_FILTER_RELOAD' => 1,
  'PRICE_FILTER_NAME_1' => 
  array (
    'en' => '0 to 24',
  ),
  'PRICE_FILTER_FROM_1' => 0,
  'PRICE_FILTER_TO_1' => 24,
  'PRICE_FILTER_NAME_2' => 
  array (
    'en' => '25 to 49',
  ),
  'PRICE_FILTER_FROM_2' => 25,
  'PRICE_FILTER_TO_2' => 49,
  'PRICE_FILTER_NAME_3' => 
  array (
    'en' => '50 to 99',
  ),
  'PRICE_FILTER_FROM_3' => 50,
  'PRICE_FILTER_TO_3' => 99,
  'PRICE_FILTER_NAME_4' => 
  array (
    'en' => '100 to 199',
  ),
  'PRICE_FILTER_FROM_4' => 100,
  'PRICE_FILTER_TO_4' => 199,
  'PRICE_FILTER_NAME_5' => 
  array (
    'en' => '200 to 499',
  ),
  'PRICE_FILTER_FROM_5' => 200,
  'PRICE_FILTER_TO_5' => 499,
  'PRICE_FILTER_NAME_6' => 
  array (
    'en' => '500 to 999',
  ),
  'PRICE_FILTER_FROM_6' => 500,
  'PRICE_FILTER_TO_6' => 999,
  'PRICE_FILTER_NAME_7' => 
  array (
    'en' => '1000 to 1999',
  ),
  'PRICE_FILTER_FROM_7' => 1000,
  'PRICE_FILTER_TO_7' => 1999,
  'PRICE_FILTER_NAME_8' => 
  array (
    'en' => '2000 to 4999',
  ),
  'PRICE_FILTER_FROM_8' => 2000,
  'PRICE_FILTER_TO_8' => 4999,
  'PRICE_FILTER_NAME_9' => 
  array (
    'en' => '5000 to 9999',
  ),
  'PRICE_FILTER_FROM_9' => 5000,
  'PRICE_FILTER_TO_9' => 9999,
  'PRICE_FILTER_NAME_10' => 
  array (
    'en' => 'More than 10000',
  ),
  'PRICE_FILTER_FROM_10' => 10000,
  'PRICE_FILTER_TO_10' => '10000000000.00',
  'USER_COUNT_RECENT_ORDERS' => 2,
  'USER_ORDERS_PER_PAGE' => 5,
  'IMG_P_W_1' => 40,
  'IMG_P_H_1' => 40,
  'IMG_P_Q_1' => 80,
  'IMG_P_W_2' => 80,
  'IMG_P_H_2' => 120,
  'IMG_P_Q_2' => 80,
  'IMG_P_W_3' => 400,
  'IMG_P_H_3' => 300,
  'IMG_P_Q_3' => 80,
  'IMG_P_W_4' => 800,
  'IMG_P_H_4' => 600,
  'IMG_P_Q_4' => 80,
  '_ENLARGE_PRODUCT_THUMBNAILS_ON' => 'P_THUMB_ENLARGE_CLICK',
  'IMG_C_W_1' => 80,
  'IMG_C_H_1' => 50,
  'IMG_C_Q_1' => 80,
  'IMG_C_W_2' => 120,
  'IMG_C_H_2' => 80,
  'IMG_C_Q_2' => 80,
  'IMG_C_W_3' => 400,
  'IMG_C_H_3' => 300,
  'IMG_C_Q_3' => 80,
  'IMG_C_W_4' => 800,
  'IMG_C_H_4' => 600,
  'IMG_C_Q_4' => 80,
  'IMG_M_W_1' => 80,
  'IMG_M_H_1' => 50,
  'IMG_M_Q_1' => 80,
  'IMG_M_W_2' => 120,
  'IMG_M_H_2' => 80,
  'IMG_M_Q_2' => 80,
  'IMG_M_W_3' => 400,
  'IMG_M_H_3' => 300,
  'IMG_M_Q_3' => 80,
  'IMG_M_W_4' => 800,
  'IMG_M_H_4' => 600,
  'IMG_M_Q_4' => 80,
  'IMG_O_W_1' => 80,
  'IMG_O_H_1' => 50,
  'IMG_O_Q_1' => 80,
  'IMG_O_W_2' => 600,
  'IMG_O_H_2' => 400,
  'IMG_O_Q_2' => 80,
  'validate_IMG_P_W_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_H_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_Q_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_W_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_H_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_Q_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_W_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_H_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_Q_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_W_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_H_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_P_Q_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_W_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_H_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_Q_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_W_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_H_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_Q_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_W_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_H_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_Q_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_W_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_H_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_C_Q_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_W_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_H_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_Q_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_W_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_H_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_Q_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_W_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_H_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_Q_3' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_W_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_H_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_M_Q_4' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_W_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_H_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_Q_1' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_W_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_H_2' => 'MinValueCheck: <1: _err_not_positive>',
  'validate_IMG_O_Q_2' => 'MinValueCheck: <1: _err_not_positive>',
  'CATEGORY_MENU_TYPE' => 'CAT_MENU_FLYOUT',
  'TOP_MENU_HIDE' => 1,
  'TOP_MENU_HIDE_CATS' => 0,
  'LANG_SELECTION' => 'LANG_NAMES',
  'HIDE_SEARCH_CATS' => 0,
  'SALE_ITEMS_COUNT' => 5,
  'NEWEST_ITEMS_COUNT' => 5,
  'BESTSELLING_ITEMS_COUNT' => 5,
  'BESTSELLING_ITEMS_DAYS' => 30,
  'INVOICE_SELLER_INFO' => 
  array (
    'en' => '<a href=\'../backend.settings\'>Click here to enter seller information</a>',
  ),
  'INVOICE_LOGO' => false,
  'DISABLE_INVOICES' => 0,
  'INVOICE_SHOW_PAYMENT_INFO' => 1,
  'SHIP_LABELS_PER_ROW' => 2,
  'SHIP_LABELS_REPEAT' => 1,
  'SHIP_LABELS_COPIES' => 1,
  'NUMBER_OF_PRODUCTS_TO_INCLUDE' => 100,
  'NUMBER_OF_NEWS_POSTS_TO_INCLUDE' => 10,
  'ENABLED_FEEDS' => 
  array (
    'ALL_PRODUCTS' => 1,
    'CATEGORY_PRODUCTS' => 1,
    'NEWS_POSTS' => 1,
  ),
  'INVENTORY_TRACKING' => 'ENABLE_AND_DISPLAY',
  'INVENTORY_TRACKING_DOWNLOADABLE' => 0,
  'REQUIRE_PHONE' => 1,
  'REQUIRE_REG_ADDRESS' => 0,
  'REG_EMAIL_CONFIRM' => 0,
  'DISABLE_STATE' => 0,
  'PASSWORD_GENERATION' => 'PASSWORD_AUTO',
  'USER_FIELDS' => 
  array (
    'FIRSTNAME' => 1,
    'LASTNAME' => 1,
    'COMPANYNAME' => 1,
    'PHONE' => 1,
    'ADDRESS1' => 1,
    'ADDRESS2' => 1,
    'CITY' => 1,
    'COUNTRY' => 1,
    'STATE' => 1,
    'POSTALCODE' => 1,
  ),
  'PRIMARY_COUNTRIES' => 'US, CA',
  'ENABLED_COUNTRIES' => 
  array (
    'AF' => 1,
    'AX' => 1,
    'AL' => 1,
    'DZ' => 1,
    'AS' => 1,
    'AD' => 1,
    'AO' => 1,
    'AI' => 1,
    'AQ' => 1,
    'AG' => 1,
    'AR' => 1,
    'AM' => 1,
    'AW' => 1,
    'AU' => 1,
    'AT' => 1,
    'AZ' => 1,
    'BS' => 1,
    'BH' => 1,
    'BD' => 1,
    'BB' => 1,
    'BY' => 1,
    'BE' => 1,
    'BZ' => 1,
    'BJ' => 1,
    'BM' => 1,
    'BT' => 1,
    'BO' => 1,
    'BA' => 1,
    'BW' => 1,
    'BV' => 1,
    'BR' => 1,
    'BQ' => 1,
    'IO' => 1,
    'VG' => 1,
    'BN' => 1,
    'BG' => 1,
    'BF' => 1,
    'BI' => 1,
    'KH' => 1,
    'CM' => 1,
    'CA' => 1,
    'CT' => 1,
    'CV' => 1,
    'KY' => 1,
    'CF' => 1,
    'TD' => 1,
    'CL' => 1,
    'CN' => 1,
    'CX' => 1,
    'CC' => 1,
    'CO' => 1,
    'KM' => 1,
    'CG' => 1,
    'CD' => 1,
    'CK' => 1,
    'CR' => 1,
    'HR' => 1,
    'CU' => 1,
    'CY' => 1,
    'CZ' => 1,
    'DK' => 1,
    'DJ' => 1,
    'DM' => 1,
    'DO' => 1,
    'NQ' => 1,
    'TL' => 1,
    'EC' => 1,
    'EG' => 1,
    'SV' => 1,
    'GQ' => 1,
    'ER' => 1,
    'EE' => 1,
    'ET' => 1,
    'FK' => 1,
    'FO' => 1,
    'FJ' => 1,
    'FI' => 1,
    'FR' => 1,
    'GF' => 1,
    'PF' => 1,
    'TF' => 1,
    'FQ' => 1,
    'GA' => 1,
    'GM' => 1,
    'GE' => 1,
    'DE' => 1,
    'GH' => 1,
    'GI' => 1,
    'GR' => 1,
    'GL' => 1,
    'GD' => 1,
    'GP' => 1,
    'GU' => 1,
    'GT' => 1,
    'GN' => 1,
    'GW' => 1,
    'GY' => 1,
    'HT' => 1,
    'HM' => 1,
    'HN' => 1,
    'HK' => 1,
    'HU' => 1,
    'IS' => 1,
    'IN' => 1,
    'ID' => 1,
    'IR' => 1,
    'IQ' => 1,
    'IE' => 1,
    'IL' => 1,
    'IT' => 1,
    'CI' => 1,
    'JM' => 1,
    'JP' => 1,
    'JT' => 1,
    'JO' => 1,
    'KZ' => 1,
    'KE' => 1,
    'KI' => 1,
    'KW' => 1,
    'KG' => 1,
    'LA' => 1,
    'LV' => 1,
    'LB' => 1,
    'LS' => 1,
    'LR' => 1,
    'LY' => 1,
    'LI' => 1,
    'LT' => 1,
    'LU' => 1,
    'MO' => 1,
    'MK' => 1,
    'MG' => 1,
    'MW' => 1,
    'MY' => 1,
    'MV' => 1,
    'ML' => 1,
    'MT' => 1,
    'MH' => 1,
    'MQ' => 1,
    'MR' => 1,
    'MU' => 1,
    'YT' => 1,
    'FX' => 1,
    'MX' => 1,
    'FM' => 1,
    'MI' => 1,
    'MD' => 1,
    'MC' => 1,
    'MN' => 1,
    'MS' => 1,
    'MA' => 1,
    'MZ' => 1,
    'MM' => 1,
    'NA' => 1,
    'NR' => 1,
    'NP' => 1,
    'NL' => 1,
    'AN' => 1,
    'NC' => 1,
    'NZ' => 1,
    'NI' => 1,
    'NE' => 1,
    'NG' => 1,
    'NU' => 1,
    'NF' => 1,
    'KP' => 1,
    'VD' => 1,
    'MP' => 1,
    'NO' => 1,
    'OM' => 1,
    'QO' => 1,
    'PC' => 1,
    'PK' => 1,
    'PW' => 1,
    'PS' => 1,
    'PA' => 1,
    'PZ' => 1,
    'PG' => 1,
    'PY' => 1,
    'YD' => 1,
    'PE' => 1,
    'PH' => 1,
    'PN' => 1,
    'PL' => 1,
    'PT' => 1,
    'PR' => 1,
    'QA' => 1,
    'RE' => 1,
    'RO' => 1,
    'RU' => 1,
    'RW' => 1,
    'SH' => 1,
    'KN' => 1,
    'LC' => 1,
    'PM' => 1,
    'VC' => 1,
    'WS' => 1,
    'SM' => 1,
    'ST' => 1,
    'SA' => 1,
    'SN' => 1,
    'CS' => 1,
    'SC' => 1,
    'SL' => 1,
    'SG' => 1,
    'SK' => 1,
    'SI' => 1,
    'SB' => 1,
    'SO' => 1,
    'ZA' => 1,
    'GS' => 1,
    'KR' => 1,
    'ES' => 1,
    'LK' => 1,
    'SD' => 1,
    'SR' => 1,
    'SJ' => 1,
    'SZ' => 1,
    'SE' => 1,
    'CH' => 1,
    'SY' => 1,
    'TW' => 1,
    'TJ' => 1,
    'TZ' => 1,
    'TH' => 1,
    'TG' => 1,
    'TK' => 1,
    'TO' => 1,
    'TT' => 1,
    'TN' => 1,
    'TR' => 1,
    'TM' => 1,
    'TC' => 1,
    'TV' => 1,
    'VI' => 1,
    'UG' => 1,
    'UA' => 1,
    'AE' => 1,
    'GB' => 1,
    'US' => 1,
    'UM' => 1,
    'UY' => 1,
    'UZ' => 1,
    'VU' => 1,
    'VA' => 1,
    'VE' => 1,
    'VN' => 1,
    'WK' => 1,
    'WF' => 1,
    'EH' => 1,
    'YE' => 1,
    'ZM' => 1,
    'ZW' => 1,
  ),
  'ENABLE_CART' => 1,
  'ENABLE_WISHLISTS' => 1,
  'MIN_TOTAL' => 0,
  'MAX_TOTAL' => 0,
  'MIN_QUANT' => 0,
  'MAX_QUANT' => 0,
  'CHECKOUT_METHOD' => 'CHECKOUT_ONEPAGE',
  'DISABLE_GUEST_CHECKOUT' => 0,
  'DISABLE_GUEST_CART' => 0,
  'SKIP_CART' => 0,
  'SKIP_SHIPPING' => 1,
  'SKIP_PAYMENT' => 1,
  'CHECKOUT_CUSTOM_FIELDS' => 'CART_PAGE',
  'ENABLE_MULTIADDRESS' => 0,
  'REQUIRE_SAME_ADDRESS' => 0,
  'DISABLE_CHECKOUT_ADDRESS_STEP' => 0,
  'ENABLE_CHECKOUTDELIVERYSTEP' => 0,
  'OPC_SHOW_CART' => 0,
  'REQUIRE_TOS' => 0,
  'TOS_MESSAGE' => 
  array (
    'en' => 'I agree to the Terms of the Service',
  ),
  'TOS_OPC_ONLY' => 0,
  'HIDE_TAXES' => 0,
  'INVOICE_NUMBER_GENERATOR' => 'SequentialInvoiceNumber',
  'SequentialInvoiceNumber_START_AT' => 0,
  'SequentialInvoiceNumber_STEP' => 1,
  'SequentialInvoiceNumber_MIN_LENGTH' => 5,
  'SequentialInvoiceNumber_PREFIX' => '',
  'SequentialInvoiceNumber_SUFFIX' => '',
  'ENABLE_SHIPPING_ESTIMATE' => 1,
  'SHIP_ESTIMATE_HIDE_ENTRY' => 
  array (
  ),
  'SHIP_ESTIMATE_FIELDS' => 
  array (
    'COUNTRY' => 1,
    'STATE' => 1,
  ),
  'OFFLINE_HANDLERS' => 
  array (
    'OFFLINE1' => 1,
  ),
  'CC_ENABLE' => 1,
  'REQUIRE_CVV' => 1,
  'CC_AUTHONLY' => 1,
  'CC_HANDLER' => 'TestCreditCard',
  'EXPRESS_HANDLERS' => 
  array (
  ),
  'PAYMENT_HANDLERS' => 
  array (
  ),
  'AlertPay_EMAIL' => 'info@integry.net',
  'AlertPay_SECURITY_CODE' => '',
  'AlertPay_ITEM_NAME' => 'Shopping cart items',
  'AurigaePayment_merchant' => 11111,
  'AurigaePayment_md5' => '',
  'AurigaePayment_method' => 'KORTINSE',
  'AurigaePayment_test' => 0,
  'AuthorizeNet_login' => 'cnpdev4444',
  'AuthorizeNet_transactionKey' => 'zzzzzz6Pj3Pz6',
  'AuthorizeNet_gateway' => 'https://secure.authorize.net/gateway/transact.dll',
  'AuthorizeNetSIM_login' => '',
  'AuthorizeNetSIM_transKey' => '',
  'AuthorizeNetSIM_test' => 0,
  'BucksNet_username' => '',
  'BucksNet_password' => '',
  'BucksNet_traderID' => '',
  'BucksNet_vatID' => '',
  'BucksNet_test' => 0,
  'CCAvenue_Merchant_Id' => '',
  'CCAvenue_WorkingKey' => '',
  'CCAvenue_Currency' => 'INR',
  'CCNow_login' => '',
  'CCNow_key' => '',
  'ChronoPayGateway_productid' => '',
  'ChronoPayGateway_secret' => '',
  'CyberMUT_TPE' => '',
  'CyberMUT_societe' => '',
  'CyberMUT_key1' => '',
  'CyberMUT_key2' => '',
  'CyberMUT_bank' => 'CyberMUT_CM',
  'CyberMUT_test' => 0,
  'DibsFlexWin_merchant' => 11111,
  'DibsFlexWin_md51' => '',
  'DibsFlexWin_md52' => '',
  'DibsFlexWin_test' => 0,
  'EWayCvn_customerID' => '87654321',
  'EWayCvn_invoiceDescription' => '',
  'EWayCvn_test' => 0,
  'GTBill_MerchantID' => '',
  'GTBill_SiteID' => '',
  'GoogleCheckout_sandbox' => 0,
  'GoogleCheckout_merchant_id' => '',
  'GoogleCheckout_merchant_key' => '',
  'HsbcPci_client' => '',
  'HsbcPci_key' => '',
  'HsbcPci_currency' => '',
  'HsbcPci_capture_automatically' => 1,
  'HsbcPci_test' => 0,
  'InternetSecureMerchantLink_account' => 1234,
  'InternetSecureMerchantLink_test' => 0,
  'MoneyBookers_email' => '',
  'MoneyBookers_secretWord' => '',
  'OFFLINE_NAME_1' => 
  array (
    'en' => 'Bank Wire Transfer',
  ),
  'OFFLINE_LOGO_1' => false,
  'OFFLINE_DESCR_1' => 
  array (
    'en' => 'You can pay for your order via bank wire transfer',
  ),
  'OFFLINE_INSTR_1' => 
  array (
    'en' => 'Please transfer the money to our account AB123456 and do not forget to quote the order ID',
  ),
  'OFFLINE_NAME_2' => 
  array (
    'en' => 'Additional Offline Payment Method',
  ),
  'OFFLINE_LOGO_2' => false,
  'OFFLINE_DESCR_2' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_2' => 
  array (
    'en' => '',
  ),
  'OFFLINE_NAME_3' => 
  array (
    'en' => 'Another Offline Payment Method',
  ),
  'OFFLINE_LOGO_3' => false,
  'OFFLINE_DESCR_3' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_3' => 
  array (
    'en' => '',
  ),
  'OFFLINE_NAME_4' => 
  array (
    'en' => 'Offline method 4',
  ),
  'OFFLINE_LOGO_4' => false,
  'OFFLINE_DESCR_4' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_4' => 
  array (
    'en' => '',
  ),
  'OFFLINE_NAME_5' => 
  array (
    'en' => 'Offline method 5',
  ),
  'OFFLINE_LOGO_5' => false,
  'OFFLINE_DESCR_5' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_5' => 
  array (
    'en' => '',
  ),
  'OFFLINE_NAME_6' => 
  array (
    'en' => 'Offline method 6',
  ),
  'OFFLINE_LOGO_6' => false,
  'OFFLINE_DESCR_6' => 
  array (
    'en' => '',
  ),
  'OFFLINE_INSTR_6' => 
  array (
    'en' => '',
  ),
  'OfflineCreditCard_customCardTypes' => '',
  'OfflineCreditCard_cardTypes' => 
  array (
    'American Express' => 1,
    'Discover Card' => 1,
    'MasterCard' => 1,
    'Visa' => 1,
  ),
  'Ogone_pspid' => '',
  'Ogone_secretWord' => '',
  'Ogone_test' => 0,
  'PayMate_mid' => '',
  'PayMate_test' => 0,
  'PayPointLite_merchant' => '',
  'PayPointLite_remotepassword' => '',
  'PayPointLite_digestkey' => '',
  'PayPointLite_currency' => 'GBP',
  'PaypalDirectPayment_sandbox' => 0,
  'PaypalDirectPayment_username' => 'sandbox_api1.integry.net',
  'PaypalDirectPayment_password' => '9AURFxxxxxxxxXV',
  'PaypalDirectPayment_signature' => 'AeQ618dBMNS1xxxxxxxxxxxxxxoPUhcIj1J5p65ZAR8Pu',
  'PaypalDirectPayment_cardTypes' => 
  array (
    'Visa' => 1,
    'MasterCard' => 1,
    'American Express' => 1,
    'Discover' => 1,
  ),
  'PaypalExpressCheckout_sandbox' => 0,
  'PaypalExpressCheckout_username' => 'sandbox_api1.integry.net',
  'PaypalExpressCheckout_password' => '9AURF7SxxxxxxxxxxXV',
  'PaypalExpressCheckout_signature' => 'AeQ618dBxxxxxxxxxxxxxxxxxnzBekoPUhcIj1J5p65ZAR8Pu',
  'PaypalExpressCheckout_AUTHONLY' => 0,
  'PaypalWebsitePaymentsStandard_EMAIL' => 'info@integry.net',
  'PaypalWebsitePaymentsStandard_SANDBOX' => 0,
  'PaypalWebsitePaymentsStandard_DEF_CURRENCY' => 'USD',
  'ProtxForm_vendor' => '',
  'ProtxForm_description' => '',
  'ProtxForm_key' => '',
  'ProtxForm_mode' => 'PROTX_LIVE',
  'SaferPay_ACCOUNTID' => '99867-94913159',
  'SaferPay_DESCRIPTION' => 'Submit payment for your order',
  'TwoCheckout_account' => '477167',
  'TwoCheckout_currency' => 'USD',
  'TwoCheckout_secretWord' => 'tango',
  'TwoCheckout_test' => 0,
  'TwoCheckoutINS_account' => '477167',
  'TwoCheckoutINS_currency' => 'USD',
  'TwoCheckoutINS_secretWord' => 'tango',
  'TwoCheckoutINS_test' => 0,
  'VCS_account' => 1111,
  'VCS_description' => '',
  'WebToPay_merchantid' => '',
  'WebToPay_projectid' => '',
  'WebToPay_signaturepassword' => '',
  'WebToPay_country' => '',
  'WebToPay_test' => 0,
  'WorldPayHostedPaymentPage_account' => '',
  'WorldPayHostedPaymentPage_test' => 0,
  'ewayshared_customerID' => '87654321',
  'ewayshared_userName' => '',
  'ewayshared_invoiceDescription' => '',
  'ewayshared_country' => 'EWAY_NZ',
  'iDEALeasy_bank' => 'ABN-AMRO',
  'iDEALeasy_account' => 'TESTiDEALEASY',
  'iDEALeasy_description' => '',
  'CanadaPostShipping_merchantID' => '',
  'FedexShipping_accountNumber' => '',
  'FedexShipping_meterNumber' => '',
  'FedexShipping_apiUrl' => 'https://gatewaybeta.fedex.com/GatewayDC',
  'FedexShipping_enabledServices' => 
  array (
    'PRIORITYOVERNIGHT' => 1,
    'STANDARDOVERNIGHT' => 1,
    'FIRSTOVERNIGHT' => 1,
    'FEDEX2DAY' => 1,
    'FEDEXEXPRESSSAVER' => 1,
    'INTERNATIONALPRIORITY' => 1,
    'INTERNATIONALECONOMY' => 1,
    'INTERNATIONALFIRST' => 1,
    'FEDEX1DAYFREIGHT' => 1,
    'FEDEX2DAYFREIGHT' => 1,
    'FEDEX3DAYFREIGHT' => 1,
    'FEDEXGROUND' => 1,
    'GROUNDHOMEDELIVERY' => 1,
  ),
  'UpsShipping_accessKey' => '',
  'UpsShipping_user' => '',
  'UpsShipping_password' => '',
  'UpsShipping_enabledServices' => 
  array (
    'UPS01' => 1,
    'UPS02' => 1,
    'UPS03' => 1,
    'UPS07' => 1,
    'UPS08' => 1,
    'UPS11' => 1,
    'UPS12' => 1,
    'UPS13' => 1,
    'UPS14' => 1,
    'UPS54' => 1,
    'UPS59' => 1,
    'UPS65' => 1,
  ),
  'UspsShipping_userId' => '',
  'UspsShipping_apiUrl' => 'http://production.shippingapis.com/ShippingAPI.dll',
  'UspsShipping_domestic' => 
  array (
    'First Class' => 1,
    'Express' => 1,
    'Priority' => 1,
  ),
  'UspsShipping_size' => '',
  'UspsShipping_priorityPackageType' => '',
  'UspsShipping_isMachinable' => 1,
  'UspsShipping_international' => 
  array (
  ),
  'TRACKING_SERVICES' => 
  array (
  ),
  'GoogleAnalytics_code' => 'UA-123456',
  'FEED_KEY' => '',
  'ENABLE_SITEMAPS' => 1,
  'HTML_EMAIL' => 1,
  'NOTIFY_NEW_ORDER' => 1,
  'NOTIFY_NEW_NOTE' => 1,
  'NOTIFICATION_EMAIL' => 'shumoapp@gmail.com',
  'EMAIL_NEW_USER' => 1,
  'EMAIL_NEW_ORDER' => 1,
  'EMAIL_STATUS_UPDATE' => 1,
  'EMAIL_STATUS_UPDATE_STATUSES' => 
  array (
    'EMAIL_STATUS_UPDATE_NEW' => 1,
    'EMAIL_STATUS_UPDATE_PROCESSING' => 1,
    'EMAIL_STATUS_UPDATE_AWAITING_SHIPMENT' => 1,
    'EMAIL_STATUS_UPDATE_SHIPPED' => 1,
  ),
  'EMAIL_ORDER_CANCELLATION' => 1,
  'EMAIL_ORDERNOTE' => 1,
  'MAIN_EMAIL' => 'shumoapp@gmail.com',
  'NEWSLETTER_EMAIL' => 'shumoapp@gmail.com',
  'EMAIL_METHOD' => 'FAKE',
  'SMTP_SERVER' => '',
  'SMTP_PORT' => 25,
  'SMTP_USERNAME' => '',
  'SMTP_PASSWORD' => '',
  'UPDATE_COPY_METHOD' => 'UPDATE_FTP',
  'UPDATE_FTP_SERVER' => '',
  'UPDATE_FTP_USER' => '',
  'UPDATE_FTP_PASSWORD' => '',
  'UPDATE_FTP_DIRECTORY' => 'public_html',
  'UPDATE_REPO_1' => 'http://repo.livecart.com',
  'UPDATE_REPO_2' => 'http://extra.livecart.com',
  'UPDATE_REPO_3' => 'http://trial.livecart.com',
  'UPDATE_REPO_4' => '',
  'UPDATE_REPO_5' => '',
  'UPDATE_REPO_6' => '',
  'UPDATE_REPO_7' => '',
  'UPDATE_REPO_8' => '',
  'UPDATE_REPO_9' => '',
  'UPDATE_REPO_10' => '',
  'UPDATE_REPO_11' => '',
  'UPDATE_REPO_12' => '',
  'UPDATE_REPO_13' => '',
  'UPDATE_REPO_14' => '',
  'UPDATE_REPO_15' => '',
  'UPDATE_REPO_16' => '',
  'UPDATE_REPO_17' => '',
  'UPDATE_REPO_18' => '',
  'UPDATE_REPO_19' => '',
  'UPDATE_REPO_20' => '',
  'SSL_PAYMENT' => 0,
  'SSL_CHECKOUT' => 0,
  'SSL_CUSTOMER' => 0,
  'SSL_BACKEND' => 0,
  'SSL_DOMAIN' => '',
  'AUTO_GENERATE_SKU' => 0,
  'DEFAULT_PRODUCT_ENABLED' => 1,
  'DEFAULT_PRODUCT_TYPE' => 
  array (
    'en' => 'prod_type_0',
  ),
  'SHOW_BACKEND_LANG_FILES' => 0,
  'SHOW_BACKEND_TEMPLATE_FILES' => 0,
  'DISABLE_WYSIWYG' => 0,
  'DISABLE_TOOLBAR' => 0,
  'DISABLE_QUICKEDIT' => 0,
  'URL_REPLACE_SPECIAL_CHARS' => 1,
  'URL_301_AUTO_REDIRECT' => 1,
  'CACHE_METHOD' => 'FileCache',
  'PROXY_HOST' => '',
  'PROXY_PORT' => 0,
  'USE_DEFAULT_SESSION_HANDLER' => 0,
  'API_AUTH_METHODS' => 
  array (
  ),
  'API_SECRET_KEY_SERVER' => '',
  'SOFT_NAME' => 'LiveCart',
  'POWERED_BY_FRONTEND' => 'Powered by LiveCart Shopping Cart',
  'POWERED_BY_URL' => 'http://livecart.com/',
  'POWERED_BY_BACKEND' => '© <a href=\'http://livecart.com/\' target=\'_blank\'>UAB Integry Systems</a>, 2007-2010',
  'BACKEND_LOGO_SMALL' => 'image/promo/transparentlogo_small.png',
  'BACKEND_LOGIN_LOGO' => 'image/promo/transparentlogo.gif',
  'BACKEND_SHOW_HELP' => 1,
  'BACKEND_SHOW_FOOTER_LINKS' => 1,
  'MODULE_STATS_UPDATED' => 1433629585,
  'MODULE_STATS_NEED_UPDATING' => 0,
  'SEARCH_MODELS' => 
  array (
    'Manufacturer' => 1,
    'NewsPost' => 1,
    'StaticPage' => 1,
  ),
  'SEARCH_MODEL_PREVIEW' => 3,
  'SEARCH_MODEL_PER_PAGE' => 10,
  'ChronoPay_productid' => '',
  'ChronoPay_productname' => '',
  'ChronoPay_currency' => 'USD',
  'SHIPPING_HANDLERS' => 
  array (
  ),
  'DELIVERY_TAX' => 0,
  'DELIVERY_TAX_CLASS' => '',
  'FREE_SHIPPING_AUTO_RATE' => 1,
  'STORE_COUNTRY' => 'US',
  'STORE_STATE' => 'NY',
  'STORE_ZIP' => '',
  'STORE_CITY' => 'New York',
  'DEF_COUNTRY' => 'US',
  'DEF_STATE' => '',
  'CURRENCY_RATE_UPDATE' => 0,
  'STATIC_DOMAIN' => '',
  'BREADCRUMB_TITLE' => 'breadcrumbs',
  'MANUFACTURER_PAGE_LIST_STYLE' => 'MANPAGE_STYLE_ALL_IN_ONE_PAGE',
  'MANUFACTURER_PAGE_DISPLAY_ACTIVE' => 1,
  'MANUFACTURER_PAGE_PER_PAGE' => 0,
); ?>