<?php
if(!defined('TEST_SUITE')) require_once dirname(__FILE__) . '/../../Initialize.php';

ClassLoader::import("application.model.searchable.item.SearchableItem");
ClassLoader::import("application.model.searchable.index.SearchableConfigurationIndexing");

/**
 *
 * @package test.model.searchable
 * @author Shumoapp
 */
class SearchableConfigurationIndexingTest extends LiveCartTest
{
    /**
     * Testing the buildList private method for handling the result generated by Config->getTree()
     * If everything goes well, no exception should be generated.
     */
    public function testBuildList()
    {
        //sample output generated by Config->getTree
        $tree = array(array('Title'=>'Main', 'id'=>'00-store'));

        $localesToTestForReindexAll[] = self::getApplication()->getDefaultLanguageCode();
        $sc = new SearchableConfigurationIndexing($this->config, self::getApplication(), $localesToTestForReindexAll);

        $sc->_values = $this->config->getValues();
        try {
            $this->invokeMethod($sc, 'buildList', array($tree, null));
            $this->assertTrue(true);
        } catch(Exception $e) {
            $this->assertTrue(false);
        }
    }
}